const js = require('@eslint/js');

module.exports = [
  js.configs.recommended,
  {
    files: ['src/**/*.js', 'tests/**/*.js', 'build.js'],
    ignores: ['dist/**'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'script',
      globals: {
        chrome: 'readonly',
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        require: 'readonly',
        module: 'readonly',
        global: 'readonly',
        globalThis: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        confirm: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
      },
    },
    rules: {
      strict: 'off',
      'no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
          ignoreRestSiblings: true
        }
      ],
      'no-undef': 'error',
      'no-redeclare': ['error', { builtinGlobals: false }],
      'no-unreachable': 'error',
      'no-unused-expressions': 'error',
      'no-case-declarations': 'off',
      'no-empty': 'off',
      'no-useless-assignment': 'off',
      'preserve-caught-error': 'off',
    },
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      globals: {
        BaseTorrentHandler: 'readonly',
        GenericDownloadHandler: 'readonly',
        DelugeHandler: 'readonly',
        TransmissionHandler: 'readonly',
        QBittorrentHandler: 'readonly',
        HandlerFactory: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        chrome: 'readonly',
        importScripts: 'readonly',
        self: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        crypto: 'readonly',
        window: 'readonly',
        document: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        Headers: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        caches: 'readonly',
        MutationObserver: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        HTMLInputElement: 'readonly',
        MutationRecord: 'readonly',
        Notification: 'readonly',
        Node: 'readonly',
        MESSAGE_TYPES: 'readonly',
        STORAGE_KEYS: 'readonly',
        HANDLER_TYPES: 'readonly',
        DEFAULTS: 'readonly',
        DEFAULT_CONFIG: 'readonly',
        configUtils: 'readonly',
        hashUtils: 'readonly',
        duplicateTracker: 'readonly',
        contextMenuUtils: 'readonly',
        openReviewPopup: 'readonly',
        sendTorrentsToHandler: 'readonly',
        getTargetTabId: 'readonly',
      },
    },
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      globals: {
        jest: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        afterAll: 'readonly',
        window: 'readonly',
        document: 'readonly',
        DOMParser: 'readonly',
        navigator: 'readonly',
        MutationObserver: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        TextDecoder: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        URL: 'readonly',
        TextEncoder: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        chrome: 'readonly',
        Node: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        MessageChannel: 'readonly',
        customElements: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
        require: 'readonly',
        module: 'readonly',
        global: 'readonly',
        process: 'readonly',
        StorageEvent: 'readonly',
        EventTarget: 'readonly',
        MESSAGE_TYPES: 'readonly',
        STORAGE_KEYS: 'readonly',
        HANDLER_TYPES: 'readonly',
        DEFAULTS: 'readonly',
        DEFAULT_CONFIG: 'readonly',
        configUtils: 'readonly',
        hashUtils: 'readonly',
        duplicateTracker: 'readonly',
        contextMenuUtils: 'readonly',
        openReviewPopup: 'readonly',
        sendTorrentsToHandler: 'readonly',
        HandlerFactory: 'readonly',
        chrome: 'readonly',
        BaseTorrentHandler: 'readonly',
        GenericDownloadHandler: 'readonly',
        DelugeHandler: 'readonly',
        TransmissionHandler: 'readonly',
        QBittorrentHandler: 'readonly',
      },
    },
  },
  {
    files: ['build.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        Buffer: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
];
